# Config file for go-test-coverage github action.
# go-actor-netbox commits to keep 100% test coverage.

profile: cover.short.profile,cover.long.profile
local-prefix: "github.com/vladopajic/go-actor-netbox"
threshold:
  total: 85
exclude:
  paths:
    - examples